version: '3.8'
services:
    backend:
        build:
            context: ./server
        ports:
            - $NODE_LOCAL_PORT:$NODE_DOCKER_PORT
        environment:
            MONGO_URI: ${MONGO_URI}
        env_file: ./.env
        networks:
            - backend
            - frontend
    frontend:
        depends_on:
            - backend
        build:
            context: ./frontend
        ports:
            - $REACT_LOCAL_PORT:$REACT_DOCKER_PORT
        networks:
            - frontend

networks:
    backend:
    frontend:
