version: '3.8'
services:
    backend:
        build: ./server
        ports:
            - '4000:4000'
        environment:
            MONGO_URI: ${MONGO_URI}
        volumes:
            - ./server:/app
            - /app/node_modules

    frontend:
        build: ./frontend
        ports:
            - '8080:80'
        volumes:
            - ./frontend:/usr/src/app
            - /usr/src/app/node_modules
